"""Lightweight local vector store (numpy + joblib).

A dependency-free stand-in for a vector DB, sized for SME data (dozens–hundreds of
small chunks). Embeddings are generated by OpenAI and stored here; retrieval is
cosine similarity in numpy. The index is persisted to disk with joblib (same
pattern as the forecasting model) and reloaded when the file changes, so the API
process and the Celery worker stay in sync.

Public interface mirrors a minimal vector store: upsert / query / reset / count.
"""
from __future__ import annotations

import os
from typing import Optional

import numpy as np

MODEL_DIR = os.environ.get("ML_MODELS_DIR", "/app/ml_models")
INDEX_PATH = os.path.join(MODEL_DIR, "rag_index.pkl")

# Process-local cache, invalidated by the file's mtime so cross-process writes
# (worker indexes → API queries) are picked up.
_cache: dict = {"store": None, "mtime": None}


def _empty() -> dict:
    return {"ids": [], "embeddings": [], "documents": [], "metadatas": []}


def _load() -> dict:
    import joblib

    if not os.path.exists(INDEX_PATH):
        if _cache["store"] is None:
            _cache["store"] = _empty()
        return _cache["store"]

    mtime = os.path.getmtime(INDEX_PATH)
    if _cache["store"] is None or _cache["mtime"] != mtime:
        _cache["store"] = joblib.load(INDEX_PATH)
        _cache["mtime"] = mtime
    return _cache["store"]


def _save(store: dict) -> None:
    import joblib

    os.makedirs(os.path.dirname(INDEX_PATH), exist_ok=True)
    joblib.dump(store, INDEX_PATH)
    _cache["store"] = store
    _cache["mtime"] = os.path.getmtime(INDEX_PATH)


def reset_collection() -> None:
    """Drop everything so a re-index starts clean."""
    _save(_empty())


def upsert(ids: list[str], embeddings: list[list[float]], documents: list[str], metadatas: list[dict]) -> None:
    if not ids:
        return
    store = _load()
    pos = {doc_id: i for i, doc_id in enumerate(store["ids"])}
    for doc_id, emb, doc, meta in zip(ids, embeddings, documents, metadatas):
        emb = list(map(float, emb))
        if doc_id in pos:
            i = pos[doc_id]
            store["embeddings"][i] = emb
            store["documents"][i] = doc
            store["metadatas"][i] = meta
        else:
            pos[doc_id] = len(store["ids"])
            store["ids"].append(doc_id)
            store["embeddings"].append(emb)
            store["documents"].append(doc)
            store["metadatas"].append(meta)
    _save(store)


def query(embedding: list[float], n_results: int = 5) -> list[dict]:
    """Return the nearest stored chunks by cosine similarity."""
    store = _load()
    if not store["embeddings"]:
        return []

    matrix = np.asarray(store["embeddings"], dtype=np.float32)
    q = np.asarray(embedding, dtype=np.float32)

    matrix_norm = matrix / (np.linalg.norm(matrix, axis=1, keepdims=True) + 1e-12)
    q_norm = q / (np.linalg.norm(q) + 1e-12)
    sims = matrix_norm @ q_norm

    top = np.argsort(-sims)[:n_results]
    hits: list[dict] = []
    for i in top:
        i = int(i)
        hits.append({
            "id": store["ids"][i],
            "document": store["documents"][i],
            "metadata": store["metadatas"][i],
            "distance": float(1.0 - sims[i]),   # cosine distance
        })
    return hits


def count() -> int:
    return len(_load()["ids"])
