"""PDF report export.

Renders a weekly business report as a formatted PDF using fpdf2.
All data comes from the already-persisted Report object — no new DB queries,
no LLM calls.  Returns raw PDF bytes ready to stream as a response.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any

from fpdf import FPDF, XPos, YPos

from app.models.report import Report

# ── Colour palette (matches the dark UI accent colours approximately) ──────
ACCENT   = (108, 99, 255)   # #6c63ff — headings / accents
SUCCESS  = (34, 197, 94)    # #22c55e — positive change
DANGER   = (239, 68, 68)    # #ef4444 — negative / reorder
WARNING  = (245, 158, 11)   # #f59e0b — low stock
MUTED    = (120, 120, 140)  # secondary text
DARK     = (20, 20, 30)     # body text
LIGHT_BG = (245, 245, 250)  # alternating row fill
WHITE    = (255, 255, 255)


class _PDF(FPDF):
    """Custom FPDF subclass with header / footer."""

    def __init__(self, period_start: str, period_end: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.period_start = period_start
        self.period_end = period_end
        self.set_auto_page_break(auto=True, margin=18)
        self.set_margins(left=18, top=18, right=18)

    def header(self):
        # Accent bar across the top
        self.set_fill_color(*ACCENT)
        self.rect(0, 0, 210, 8, style="F")

        self.ln(6)
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(*ACCENT)
        self.cell(0, 8, "SoukPilot AI", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        self.set_font("Helvetica", "", 9)
        self.set_text_color(*MUTED)
        self.cell(0, 5, f"Weekly Business Report  ·  {self.period_start}  →  {self.period_end}",
                  new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.ln(3)

        # Thin divider
        self.set_draw_color(*ACCENT)
        self.set_line_width(0.4)
        self.line(18, self.get_y(), 192, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-13)
        self.set_font("Helvetica", "", 7.5)
        self.set_text_color(*MUTED)
        ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
        self.cell(0, 5, f"Generated by SoukPilot AI  ·  {ts}  ·  Page {self.page_no()}", align="C")


# ── Layout helpers ─────────────────────────────────────────────────────────

def _section_title(pdf: _PDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(*ACCENT)
    pdf.cell(0, 7, title, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_draw_color(*ACCENT)
    pdf.set_line_width(0.3)
    pdf.line(18, pdf.get_y(), 192, pdf.get_y())
    pdf.ln(3)


def _metric_row(pdf: _PDF, label: str, this_week: float, last_week: float, change_pct: Any) -> None:
    """Single row in the metrics summary table."""
    col_w = [80, 36, 36, 36]
    pdf.set_font("Helvetica", "", 9.5)
    pdf.set_text_color(*DARK)
    pdf.cell(col_w[0], 7, label)
    pdf.cell(col_w[1], 7, f"${this_week:,.2f}", align="R")
    pdf.cell(col_w[2], 7, f"${last_week:,.2f}", align="R")

    if change_pct is None:
        pdf.set_text_color(*MUTED)
        pdf.cell(col_w[3], 7, "—", align="R", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    else:
        color = SUCCESS if change_pct >= 0 else DANGER
        pdf.set_text_color(*color)
        sign = "+" if change_pct >= 0 else ""
        pdf.cell(col_w[3], 7, f"{sign}{change_pct:.1f}%", align="R",
                 new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(*DARK)


def _table_header(pdf: _PDF, columns: list[tuple[str, int]]) -> None:
    """Render a shaded table header row."""
    pdf.set_fill_color(*LIGHT_BG)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(*MUTED)
    for label, w in columns:
        pdf.cell(w, 6, label.upper(), fill=True)
    pdf.ln()


def _table_row(pdf: _PDF, cells: list[tuple[str, int]], shade: bool = False, color=None) -> None:
    if shade:
        pdf.set_fill_color(*LIGHT_BG)
    fill = shade
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*(color or DARK))
    for text, w in cells:
        pdf.cell(w, 6, str(text), fill=fill)
    pdf.ln()
    pdf.set_text_color(*DARK)


# ── Main export function ────────────────────────────────────────────────────

def build_report_pdf(report: Report) -> bytes:
    """Render *report* as a PDF and return the raw bytes."""
    data: dict = report.data_json or {}
    period = data.get("period", {})
    start = str(period.get("start", report.period_start or ""))
    end   = str(period.get("end",   report.period_end   or ""))

    pdf = _PDF(period_start=start, period_end=end)
    pdf.add_page()

    # ── 1. AI Narrative ──────────────────────────────────────────────────
    if report.summary_text:
        _section_title(pdf, "Business Summary")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(*DARK)
        pdf.multi_cell(0, 6, report.summary_text)
        pdf.ln(4)

    # ── 2. Key Metrics ───────────────────────────────────────────────────
    _section_title(pdf, "Key Metrics")

    # Column headers
    col_w = [80, 36, 36, 36]
    pdf.set_fill_color(*LIGHT_BG)
    pdf.set_font("Helvetica", "B", 8.5)
    pdf.set_text_color(*MUTED)
    for label, w in zip(["Metric", "This Week", "Last Week", "Change"], col_w):
        pdf.cell(w, 6, label.upper(), fill=True)
    pdf.ln()

    sales  = data.get("sales", {})
    profit = data.get("profit", {})
    _metric_row(pdf, "Revenue", sales.get("this_week", 0), sales.get("last_week", 0), sales.get("change_pct"))
    _metric_row(pdf, "Gross Profit", profit.get("this_week", 0), profit.get("last_week", 0), profit.get("change_pct"))

    # Most / least profitable
    most   = data.get("most_profitable")
    least  = data.get("least_profitable")
    if most or least:
        pdf.ln(2)
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(*MUTED)
        if most and most.get("margin_pct") is not None:
            pdf.cell(0, 5, f"Most profitable product:  {most['name']}  ({most['margin_pct']}% margin)",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        if least and least.get("margin_pct") is not None:
            pdf.cell(0, 5, f"Least profitable product: {least['name']}  ({least['margin_pct']}% margin)",
                     new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.ln(4)

    # ── 3. Top Products ──────────────────────────────────────────────────
    top_products: list[dict] = data.get("top_products", [])
    if top_products:
        _section_title(pdf, "Top Products by Revenue")
        cols = [("Product", 100), ("Revenue", 40), ("Units Sold", 34)]
        _table_header(pdf, cols)
        for i, p in enumerate(top_products):
            _table_row(pdf, [
                (p.get("name", "—"), 100),
                (f"${float(p.get('revenue', 0)):,.2f}", 40),
                (str(p.get("units", "—")), 34),
            ], shade=(i % 2 == 1))
        pdf.ln(4)

    # ── 4. Reorder Risks ────────────────────────────────────────────────
    risks: list[dict] = data.get("low_stock_risks", [])
    if risks:
        _section_title(pdf, "Reorder Risks")
        cols = [("Product", 100), ("Stock Left", 40), ("Days Until Stockout", 34)]
        _table_header(pdf, cols)
        for i, r in enumerate(risks):
            days = r.get("days_until_stockout")
            days_str = f"{days:.1f}" if days is not None else "—"
            _table_row(pdf, [
                (r.get("name", "—"), 100),
                (str(r.get("current_stock", "—")), 40),
                (days_str, 34),
            ], shade=(i % 2 == 1), color=DANGER)
        pdf.ln(4)

    # ── 5. Supplier Price Changes ────────────────────────────────────────
    price_changes: list[dict] = data.get("supplier_price_changes", [])
    if price_changes:
        _section_title(pdf, "Supplier Price Changes This Week")
        cols = [("Supplier", 70), ("Product", 70), ("Change", 34)]
        _table_header(pdf, cols)
        for i, c in enumerate(price_changes):
            pct = float(c.get("change_pct", 0))
            color = DANGER if pct > 0 else SUCCESS
            sign = "+" if pct > 0 else ""
            _table_row(pdf, [
                (c.get("supplier", "—"), 70),
                (c.get("product", "—"), 70),
                (f"{sign}{pct:.1f}%", 34),
            ], shade=(i % 2 == 1), color=color)
        pdf.ln(4)

    return bytes(pdf.output())
